(() => {
  const request = JSON.parse(sessionStorage.getItem('aiplay_lesson_request') || '{"topic":"SQL joins","level":"Beginner"}');
  const presets = {
    'sql joins': {intro:'Joins let you combine useful information stored in separate tables.',explanation:'A database usually keeps related information in different tables. A join matches rows between those tables using a shared value, such as customer_id. It lets one query answer questions that need information from more than one place.',concepts:['A key is the value used to match related rows.','INNER JOIN keeps rows that have a match on both sides.','LEFT JOIN keeps every row from the left table.'],analogy:'Imagine matching each library card with the books checked out using the card number.',hookTitle:'Match, then merge',hook:'Remember: a JOIN finds matching values first, then shows the related information.'},
    'python loops': {intro:'Loops repeat a block of code so you do not have to write the same instruction again.',explanation:'A loop gives a computer a repeatable task. A for loop goes through a known collection or range; a while loop continues while a condition is true. Good loops change or finish in a clear way.',concepts:['for loops iterate through items or a range.','while loops continue while their condition stays true.','Indentation defines the code that belongs inside a loop.'],analogy:'A loop is like reading every name on a class register, one line at a time.',hookTitle:'Repeat with a reason',hook:'Ask two questions: What repeats? When does it stop?'},
    'photosynthesis': {intro:'Photosynthesis is how plants turn light energy into stored chemical energy.',explanation:'Plants use sunlight, water, and carbon dioxide to make glucose, their food. Oxygen is released as a result. This process happens mainly in chloroplasts, which contain the green pigment chlorophyll.',concepts:['Light provides the energy for the process.','Water and carbon dioxide are the raw materials.','Glucose stores energy; oxygen is released.'],analogy:'Think of a leaf as a solar-powered kitchen that makes food from air and water.',hookTitle:'Light in, food made',hook:'Sunlight + water + carbon dioxide → glucose + oxygen.'},
    "newton's laws": {intro:'Newton’s laws explain how forces change the motion of objects.',explanation:'The first law says motion does not change unless a net force acts. The second connects force, mass, and acceleration. The third says forces come in equal and opposite pairs on different objects.',concepts:['Inertia resists changes in motion.','More net force creates more acceleration for the same mass.','Action–reaction forces act on different objects.'],analogy:'A shopping cart is harder to accelerate when it is full because it has more mass.',hookTitle:'Force changes motion',hook:'First: resist change. Second: F = ma. Third: forces come in pairs.'}
  };
  const key = Object.keys(presets).find(name => request.topic.toLowerCase().includes(name));
  const data = presets[key] || {intro:`Build a fast, focused understanding of ${request.topic}.`,explanation:`Start with the core definition of ${request.topic}, then connect it to one clear example and explain it in your own words. This learning card is ready for a connected AI lesson service to add accurate topic-specific detail.`,concepts:['Define the main idea in one sentence.','Identify an example or real-world use.','Explain the topic aloud without looking at notes.'],analogy:'Use a familiar example to connect the new idea to something you already know.',hookTitle:'Explain, recall, repeat',hook:'The fastest way to remember a topic is to retrieve it, not only reread it.'};
  const fill = (id, value) => document.querySelector(id).textContent = value;
  setTimeout(() => { document.querySelector('#loading').hidden = true; document.querySelector('#lesson').hidden = false; fill('#levelBadge', request.level.toUpperCase() + ' PATH'); fill('#lessonTitle', request.topic); fill('#intro', data.intro); fill('#explanation', data.explanation); fill('#analogy', data.analogy); fill('#hookTitle', data.hookTitle); fill('#hook', data.hook); fill('#conceptCount', data.concepts.length); const list = document.querySelector('#concepts'); data.concepts.forEach(concept => { const item = document.createElement('li'); item.textContent = concept; list.append(item); }); sessionStorage.setItem('aiplay_active_lesson', JSON.stringify({topic:request.topic, concepts:data.concepts, hook:data.hook})); }, 650);
  document.querySelector('#playButton').addEventListener('click', () => window.location.assign('recall.html'));
})();
